# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# Oh-My-Zsh configuration
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME=""  # Starship handles the prompt

plugins=(
    git
    fzf
    zsh-syntax-highlighting
    zsh-autosuggestions
    zsh-history-substring-search
    you-should-use
    zsh-bat
)

source $ZSH/oh-my-zsh.sh

# All the default Omarchy aliases and functions
# (don't mess with these directly, just overwrite them here!)
source ~/.local/share/omarchy/default/zsh/rc

# Add your own exports, aliases, and functions here.
#
# Make an alias for invoking commands you use constantly
# alias p='python'
